name: 'Push al repo'
description: 'Si se ha modificado previamente el stock se debe hacer un push al repo con el nuevo fichero de data.json'

permissions:
  contents: write
  pages: write
  id-token: write

runs:
  using: "composite"
  steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Run Python Stock Updates
      shell: bash
      run: |
        rm data.json
        pip install --upgrade pip
        pip install pandas
        python stock.py

    - name: Push al repo
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data.json
        git commit -m "Modificación automática del fichero de stock"
        git push
